### ISSUE TITLE
Update plugin version 

### ISSUE THREAD

**Issue by w7shdev** [PhazeRoOman/thawani-for-woocommerce#100]
## Short description 

I saw the release is 1.4.0 and the plugin version is still at 1.3.0 we need to sync this. 
Also we need to update the version in README.txt

https://github.com/PhazeRoOman/thawani-for-woocommerce/blob/dae55252cace058fd75397001d2d38f44b396a26/thawani-for-woocommerce.php#L9

**Comment by DevAseel** [comment]
@w7shdev Thank you for flagging this, working on it.
