### ISSUE TITLE
Hello, I have a problem with Checkout  When the payment process is rejected and shown (Error processing order completion. Please try again)

### ISSUE THREAD

**Issue by zeaadalhosni** [PhazeRoOman/thawani-for-woocommerce#105]
![9876](https://github.com/PhazeRoOman/thawani-for-woocommerce/assets/147494315/5e181064-0d22-430f-8e49-5d5cd5ef27fa)

![456](https://github.com/PhazeRoOman/thawani-for-woocommerce/assets/147494315/885dc305-626a-4579-9e81-14c2012c50cd)

Even though all the correct information has been entered

**Comment by w7shdev** [comment]
hey @zeaadalhosni 
I can see that the keys used for the setting _are not the public one provided by Thawani Pay in the documetnation page_.
the keys can be found at the bottom of [Thawani pay checkout](https://thawani-technologies.stoplight.io/docs/thawani-ecommerce-api/5534c91789a48-thawani-e-commerce-api). 

if the keys are generated for the production the you have to set it up to the production environment,

**Comment by zeaadalhosni** [comment]
![7808](https://github.com/PhazeRoOman/thawani-for-woocommerce/assets/147494315/ca3880fd-0b34-4eaf-925b-03d26b30a170)
![987](https://github.com/PhazeRoOman/thawani-for-woocommerce/assets/147494315/46641aa3-b597-4027-a692-ef6d7c6b2026)
![567](https://github.com/PhazeRoOman/thawani-for-woocommerce/assets/147494315/99ffec72-e5ca-46c7-b0a6-163ff2486c00

Unfortunately, the same problem remains

**Comment by zeaadalhosni** [comment]
Unfortunately, the same problem remains

![567](https://github.com/PhazeRoOman/thawani-for-woocommerce/assets/147494315/c91d4b6b-d3ae-4245-bd6f-dbb09c048386)
![7808](https://github.com/PhazeRoOman/thawani-for-woocommerce/assets/147494315/e2bcd323-6d72-49e4-b7ab-62c0c8c7df5f)

![987](https://github.com/PhazeRoOman/thawani-for-woocommerce/assets/147494315/4d6ef6a0-5184-4f16-945d-3d2e48ebd9ef)

**Comment by w7shdev** [comment]
Hala. @zeaadalhosni .. I'm not sure if the production keys are active. please see here https://github.com/PhazeRoOman/thawani-for-woocommerce/issues/90#issuecomment-1221318338

please check the development environment with development keys and if the checkout works then I believe it's an activation problem.

**Comment by zeaadalhosni** [comment]
Is Publishable Key the same as Public Key?

**Comment by w7shdev** [comment]
> Is Publishable Key the same as Public Key?

yes
