### ISSUE TITLE
Multiple Public & Secret Key depend on the merchant

### ISSUE THREAD

**Issue by Mostafazzz115** [PhazeRoOman/thawani-for-woocommerce#106]
Hi
is it possible to make the Secret key and publishable key accept multiple values ?! 
for example if we have 3 vendors, each vendor can add his own secret and public key, and assume vendor 1 added them, so when a customer buy his products he will pay through the first P & S keys, when another customer buy products of No 2 vendor, he will pay through the second P & S keys and etc... 
is it possible ?! 
please respond ASAP 
Thank you ...

**Comment by w7shdev** [comment]
Hello, 
No it's not possible.

**Comment by Mostafazzz115** [comment]
Hi, thanks for reply 
can you briefly explain why so I can show it to the client 
Thank you
