### ISSUE TITLE
Thawani Payment Option does not show in checkout screen

### ISSUE THREAD

**Issue by zaabi1995** [PhazeRoOman/thawani-for-woocommerce#107]
Description:
The Thawani Payment Option does not appear in the checkout screen when using the Twenty Four theme in WooCommerce on WordPress.

Steps to Reproduce:

Install and activate the Twenty Four theme on WordPress.
Setup WooCommerce and configure the Thawani Payment Gateway.
Navigate to the checkout screen as a customer.
Expected Behavior:
The Thawani Payment Option should be visible and selectable on the checkout screen.

Actual Behavior:
The Thawani Payment Option is not displayed on the checkout screen.

<img width="787" alt="image" src="https://github.com/PhazeRoOman/thawani-for-woocommerce/assets/34938610/b1c8a9ff-623a-4eaa-bb8f-13d2ac2b493a">

<img width="1211" alt="image" src="https://github.com/PhazeRoOman/thawani-for-woocommerce/assets/34938610/2f4c6dd1-2299-4b8c-a978-6d01918a7ccd">

<img width="665" alt="image" src="https://github.com/PhazeRoOman/thawani-for-woocommerce/assets/34938610/3c725bbf-0a70-49a0-88ad-e3903c2e42f0">

**Comment by DevAseel** [comment]
@zaabi1995 Thank you for bringing up this issue. It appears that the recent release of WordPress has introduced some significant changes that are causing compatibility issues. As a result, the current version of the Thawani Plugin is not compatible with this updated version of WordPress, which is why you're experiencing this expected behavior.

**Comment by zaabi1995** [comment]
Thank you, would there be a plan to fix it?

Best Regards,


Ali Adnan Haider Darwish

Specialist Business Planner

Sector Development & Promotion


________________________________

**Comment by DevAseel** [comment]
Hey again, @zaabi1995. 

We are planning to support the new version of WordPress, we will keep you updated.

**Comment by DevAseel** [comment]
Closing this one out as there's already another [open issue](https://github.com/PhazeRoOman/thawani-for-woocommerce/issues/108) for it.
