### ISSUE TITLE
The Thawani plugin is not working on the woocommerce last version 

### ISSUE THREAD

**Issue by abdullaherp** [PhazeRoOman/thawani-for-woocommerce#108]
Hi Sir 
The Thawani plugin is not working on the woocommerce last version 
Please can you update this plugin?
it is a very good plugin and helps us a lot 
Thank you 
Abdullah

**Comment by DevAseel** [comment]
Hey Abdullah! 

Thank you for creating the issue, we are aware of the breaking change introduced by the new version of WordPress and we will be working on releasing a supported version.

**Comment by abdullaherp** [comment]
Dear Sir 
Thank you for your update 
Is there a release date for the new version of the Thwani plugin? because we are waiting for the new version 
Please tell us when the new version of Thwani will be available!
Thank you 
Abdullah

**Comment by zaabi1995** [comment]
Will it be fixed?
