### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by zaabi1995** [PhazeRoOman/thawani-for-woocommerce#110]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by w7shdev** [comment]
hello @zaabi1995 
can you elaborate on the issue title ?  the message is not clear

**Comment by HAMIDM80** [comment]
i have the same problem ,
not working
wordpress Current version: 6.6.1
Thawani Payments Gateway for Woocommerce.

Version 1.4.1
WooCommerce Version 9.1.2

![Untitled](https://github.com/user-attachments/assets/cb009c54-1404-44f7-8e0d-d638944889bc)
