### ISSUE TITLE
[Urgent] It doesn't redirect, neither count the order as paid. please help (video included)

### ISSUE THREAD

**Issue by mhmahran** [PhazeRoOman/thawani-for-woocommerce#111]
The Problem is Explained in This video detailed, please respond as soon as possible.

https://streamable.com/y9200g

**Comment by w7shdev** [comment]
hello  @mhmahran 
thank you for opening the issue , this is not the behaviour of the plugin 
let me explain to you .. 

1. the website should redirect into a path where the site will check the session with thawani 
https://github.com/PhazeRoOman/thawani-for-woocommerce/blob/master/src/WC_Gateway_ThawaniGateway.php#L137-L146
it seems that the link(path) is not exists in your site ... 


for the logs it just a statements of printing the expected results 
https://github.com/PhazeRoOman/thawani-for-woocommerce/blob/master/src/WC_Gateway_ThawaniGateway.php#L433-L438

if the plugin __had an issue then you will never see thawani page__. 

make sure that the path of the redirect from thawani exists 
```
https://yoursitename.com/wc-api/thawani_gw?ref=order_id
```

**Comment by mhmahran** [comment]
Thank you, solved.
