### ISSUE TITLE
اشعار الدفع

### ISSUE THREAD

**Issue by aliq009** [PhazeRoOman/thawani-for-woocommerce#114]
بعد ان تتم عملية الدفع الموقع لا يتعرف عليها ولاكن يتم خصم المبلغ من بطاقة العميل .عند التحقق من الطلب في ووكومرس يضهر انه في انتضار الدفع  
مع العلم انه استلم المبلغ المدفوع

**Comment by w7shdev** [comment]
مرحبا، @aliq009 
في حالة حدوث مثل هذا الخطأ - على الارجح أعدادت الموقع في انشاء الرابط 
اتبع خطوات التثبيت الموجودةفي الصفحة الرئيسية للاضافة https://github.com/PhazeRoOman/thawani-for-woocommerce?tab=readme-ov-file

**Comment by aliq009** [comment]
اهلا
اتبعت الخطوات بس الحين يضهر انه في مشكله في رسوم الاضافه 
![Screenshot 127 210853](https://github.com/user-attachments/assets/9d580c23-124a-4554-bdf2-5f8daa6c2b67)
