### ISSUE TITLE
Add a hyperlink + correct spelling error

### ISSUE THREAD

**Issue by jeanansabry** [PhazeRoOman/thawani-for-woocommerce#55]
- Create a hyperlink in "License" section: word "LICENSE" should link to website: https://github.com/PhazeRoOman/thawani-for-woocommerce/blob/master/LICENSE.md

- Spelling error in "Frequently asked questions" section: word "teh" > correction "the"

**Comment by PuneetDabral** [comment]
mam can i ?

**Comment by Ma7eer** [comment]
Greetings @PuneetDabral this issue has been assigned to @jeanansabry However, be on the lookout. We will be adding more issues and would love your contribution!

**Comment by PuneetDabral** [comment]
ok sir i am eagerly waiting to work with you....! give me a chance so i can contribute my first contribution and learn more ...
