### ISSUE TITLE
A problem when trying to upload the plugin

### ISSUE THREAD

**Issue by loayjah** [PhazeRoOman/thawani-for-woocommerce#59]
### This issue addresses:
- [x] A suggestion for improvement: Add this issue on the documentation in case someone comes across it.

## Description:
- I have come across a problem when trying to upload the plugin that took me about an hour to solve. The problem is after selecting the plugin and clicking upload the following message shows up: "The link you followed has expired. Please try again". As [this snapshot](https://phazero-my.sharepoint.com/:i:/g/personal/loay_aljahwari_phaze_ro/EfTDL_trVKlFo4u_yXV-N7cBfmOArQr8NbyQuR16rwxhwQ?e=chDvZP) illustrates.

- I tried to increase the maximum uploading size after reading a solution on the internet, but that didn't work. So I had to go around this by downloading WP File Manager plugin and upload the **unzipped plugin's folder** from there.

#### What issues does this bug cause:

The user is unable to upload/install the plugin

#### How can this bug be recreated:
- Go to the **Dashboard**
- Hover over **Plugins** option and then click on **Add New**
- Click on **Upload Plugin** at the top of the page
- **Browse**, **select file**, and **open file**
- Click on **Install Now**
- The error is displayed

#### Potential Fix (If cause known):
- Unzip the Thawani Plugin file
- Install **WP File Manager** Plugin from WordPress Plugin Directory
- From the Dashboard menu options click on the WP File Manager
- Browse to the following directory: wp-content -> plugins
- Right click and then select Upload files option -> Select Folder
- Select the Thawani Plugin Folder that you unzipped previously
- From the Dashboard menu options go to Plugins -> Thawani for WooCommerce -> Activiate
- Follow the steps on the documentation how to set it up

#### WordPress Environment Versions:
- Wordpress Version: 5.8.1 
- WooCommerce Version: 5.6.0

**Comment by w7shdev** [comment]
Hi @loayjah can you reproduce the issue by uploading this [download from here](https://github.com/PhazeRoOman/thawani-for-woocommerce/releases/download/v1.2.0/thawani-for-woocommerce.zip)

P.S when sharing issue just upload the image by drag and drop so it can show up in the context

**Comment by loayjah** [comment]
Yes, it works now. What was the issue?

**Comment by w7shdev** [comment]
closed
