### ISSUE TITLE
UI : add button to get the order status 

### ISSUE THREAD

**Issue by w7shdev** [PhazeRoOman/thawani-for-woocommerce#72]
due sometimes a lagging on the payment, a success payment may return to fail. this is a rare situation.
for that we need to add a button to get the wordpress status if the payment success (in Thawani Pay) but it's failed on the  wordpress.

**Comment by HajerSubhi** [comment]
@w7shdev Can you elaborate more on this and if you screenshot or an idea of how this should look?

**Comment by w7shdev** [comment]
> @w7shdev Can you elaborate more on this and if you screenshot or an idea of how this should look?

Long story short: 
Thawani pay is layer on top of Oman NET and sometime some lagging happens where the payment deduct and the payment status returns cancelled.  After some minutes it update to be success. _this is a rare case_. 

**Suggestion here**
to add a button to get the status on the table where the order ID id displayed. 

There is an issue with the design. 
that's why we are planning on re-factor it.

**Comment by HajerSubhi** [comment]
Do you mean here?

![image](https://user-images.githubusercontent.com/54309414/145368754-f75fcc7b-99a5-40d7-9f87-7e82dbc3e079.png)

**Comment by w7shdev** [comment]
Yes, we can sync to discuss this

**Comment by HajerSubhi** [comment]
@w7shdev How should the UI look like? What other than order id should be there?

**Comment by w7shdev** [comment]
> @w7shdev How should the UI look like? What other than order status should be there?

@HajerSubhi as we disccussed we need to map the order ID to WooCommerce page. Once the user clicks on the link a new tab will open for the order page ( admin side )..

**Comment by HajerSubhi** [comment]
@w7shdev Can I add this issue to the opened [PR](https://github.com/PhazeRoOman/thawani-for-woocommerce/pull/69) instead of creating a seprate one?
