### ISSUE TITLE
Thawani Gateway Session History: Shows un-realtead information

### ISSUE THREAD

**Issue by HajerSubhi** [PhazeRoOman/thawani-for-woocommerce#75]
I created an e-commerce website to test the plugin and I made one payment which was successful. However, when I went to the session history there were other payments that are not related to my shop.\

![image](https://user-images.githubusercontent.com/54309414/145369590-31f77c30-5680-4e0c-adc3-39582f526e1b.png)

Is it supposed to show all those information?

**Comment by w7shdev** [comment]
> I created an e-commerce website to test the plugin and I made one payment which was successful. However, when I went to the session history there were other payments that are not related to my shop.\
> 
> ![image](https://user-images.githubusercontent.com/54309414/145369590-31f77c30-5680-4e0c-adc3-39582f526e1b.png)
> 
> Is it supposed to show all those information?

You are using a keys that's why you have a lot of un related data. this has nothing to do with the plugin.
