### ISSUE TITLE
Logs are not working 

### ISSUE THREAD

**Issue by Laithozad** [PhazeRoOman/thawani-for-woocommerce#77]
**Describe the bug**

I'm trying to integrate with my website. We followed all of the steps, but the logs aren't working. 
Please take a look at the image attached.

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/97837109/149662471-437404e3-e526-4d1d-9555-d9342b2a169c.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by w7shdev** [comment]
Hey @Laithozad , Thanks for opening the issue

I've tested the plugin in the development ( UAT ) environment and it works without any issue. 

**To investigate your issue, use the following points as a check list**

1. The currency at the checkout must be OMR. 
2. Make sure all the inputs are required in the checkout field ( email, name, phone number) 
3. Make sure that the UAT keys works fine in the development mode 
4. Make sure that the Keys are activated with Thawani Pay ( Thawani Pay will active your account to be applicable in the production mode) . 


if those 4 points did not work then let me know

**Comment by Laithozad** [comment]
Hi Muhannad, 

I have checked all things in the list but still same issue, please check the attached pictures.

Regards,

**Comment by w7shdev** [comment]
@Laithozad I'll send you an invitation for google meeting, because the context is not enough at the moment
