### ISSUE TITLE
Shipping fee is showing without Vat

### ISSUE THREAD

**Issue by Hadhab** [PhazeRoOman/thawani-for-woocommerce#80]
Delivery fee showing without VAT in Thawani Checkout

**Comment by w7shdev** [comment]
Hey @Hadhab , let me understand that you want to add VAT to a shipping fee ? if yes then this can not be done.
You can customize it to fit your needs.

**Comment by Hadhab** [comment]
In Oman, according to the regulations, we have to add VAT to any goods and services.

**Comment by Hadhab** [comment]
Pls do let me know where should I change the codes to add VAT to the Delivery Charge

**Comment by w7shdev** [comment]
@Hadhab it will be here 
https://github.com/PhazeRoOman/thawani-for-woocommerce/blob/f08f2903349dca355e2be1e5d6bbb27d83645686/src/WC_Gateway_ThawaniGateway.php#L359-L366
