### ISSUE TITLE
VAT Calculation error + Invalid Success Link connection to WooCommerce 

### ISSUE THREAD

**Issue by behzad1628** [PhazeRoOman/thawani-for-woocommerce#81]
**Describe the bug**
Dear 

As per the attached documents , we have placed an order for total value of 1.60 Rial (VAT Included). However :
1. Once we click on PAY ONLINE , the amount which is deducting from the account is OMR 1.596
2. Once the payment is done, we are redirected to EROR 404 because the success link between the plugin and the Woo commerce does not work properly.

![WhatsApp Image 2022-03-02 at 23 48 59](https://user-images.githubusercontent.com/94117791/156523758-8f60630e-2d35-4438-9e1a-7f65a0dc4084.jpeg)
![WhatsApp Image 2022-03-02 at 23 49 22](https://user-images.githubusercontent.com/94117791/156523764-a00ddfa4-7a32-4de0-8fc4-9de801c3f6bf.jpeg)

**Comment by w7shdev** [comment]
Hey @behzad1628 

First point I could not replicated on my end I have set the tax to 5% and the calculation is set correctly. if  you want to round the amount then you should configure your WooCommerce correctly.

The second point can be misconfiguration please follow the documentation of the installation https://github.com/PhazeRoOman/thawani-for-woocommerce#installation

Make sure that your wordpress **Permalink Settings** is set same as the documentation
