### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by Hadhab** [PhazeRoOman/thawani-for-woocommerce#82]
Showing server error when using points discount

**Comment by Hadhab** [comment]
My website: www.hadhab.com

**Comment by Hadhab** [comment]
Also is not generated from wp-admin

**Comment by w7shdev** [comment]
Hey @Hadhab 
this is a duplicate of #50  and #51 . 

TL;DR

Thawani Pay API, is not supporting coupon discount by design. So you have to work around this and communicate it with Thawani Pay support.

**Comment by w7shdev** [comment]
@Ma7eer can we close this out

**Comment by Hadhab** [comment]
Yes, thank you for the support
