### ISSUE TITLE
Three decimal Pricing that do not end in 0 produces an error

### ISSUE THREAD

**Issue by zaabi1995** [PhazeRoOman/thawani-for-woocommerce#86]
**Describe the bug**
When the product price ends with anything but 0 for prices of 3 decimal places for OMR it produces an error.

**Additional context**
{"success":false,"code":4000,"description":"Invalid information","data":{"error":[{"field":"products[0].unit_amount","message":"Input string '952.381000000000085492501966655254364013671875' is not a valid integer. Path 'products[0].unit_amount', line 1, position 125."}]}}

{"success":false,"code":4000,"description":"Invalid information","data":{"error":[{"field":"products[0]._unit_amount","message":"The field UnitAmount must be between 100 and 9999000."}]}}

**Comment by w7shdev** [comment]
hey @zaabi1995 can I know the price that set on woocommerce for the product ?

**Comment by w7shdev** [comment]
confirmed it's a bug ! thanks @zaabi1995

**Comment by zaabi1995** [comment]
Any price that does not end in 0 causes the bug

**Comment by zaabi1995** [comment]
How do I update the plugin?
