### ISSUE TITLE
There is an error that appears when paying on the checkout page

### ISSUE THREAD

**Issue by ahmed-91** [PhazeRoOman/thawani-for-woocommerce#89]
Describe the bug
I am trying to make a purchase of products and select the payment method again, it shows an error
Error while processing request completion. Please try again.

**Comment by w7shdev** [comment]
hey @ahmed-91 

I hope you solved your issue by now .. in case you didn't please  check bellow 


--- 


can you let me know which version are you using ? 
to find out -> head to admin dashboard -> plugins -> look for thawani-for-woocommerce version? 

it seems there are many missing details 
for stater which environment your are trying to checkout with ? are the keys valid ? what is the currency on the checkout page ? what are the prices of the product

**Comment by w7shdev** [comment]
Closing this because there is not response!
