### ISSUE TITLE
There is an error that appears when paying on the checkout page

### ISSUE THREAD

**Issue by ahmed-91** [PhazeRoOman/thawani-for-woocommerce#90]
Describe the bug
I am trying to make a purchase of products and select the payment method again, it shows an error
Error while processing request completion. Please try again.

I hope you solved your issue by now .. in case you didn't please check bellow

can you let me know which version are you using ?
Version 1.3.0

Correct keys attached to the picture have been used
https://ibb.co/sKfqghR

Country: Oman
Currency: Omani Rial

**Comment by ahmed-91** [comment]
Additional Attachments

https://ibb.co/GPRLzgr
https://ibb.co/LJrCVdD

**Comment by w7shdev** [comment]
hey @ahmed-91  from where you have downloaded the last version is it from the readme me , if yes then please use this one https://github.com/PhazeRoOman/thawani-for-woocommerce/discussions/88 , this version was not released yet! 

> I was but not mapped to a tag 

I hope you resolved the issue by now. 

ping to PhazeRo team to make release tags @Ma7eer @Maher9596 @MasoudRawahi 

if the given update did not solve the issue , please re-open this issue again .. 


Some notes 

1. Make sure that you are able to checkout with development keys , if the production keys did not work then please contact Thawani pay team to enable the production keys for you.. 
2. Thawani pay team will request a sample of the response of a success checkout you can generate one and give it to them , in case you don't have a technical experience on this matter we created a plugin you can use it https://github.com/PhazeRoOman/get_thawani_response
3. If the points mentioned above are satisfied and the checkout still did not work then please let's know
