### ISSUE TITLE
Tax Amount

### ISSUE THREAD

**Issue by ghulamostafa** [PhazeRoOman/thawani-for-woocommerce#93]
It would be really good if the tax amount could be passed as a separate line item in Thawani since Thawani currently does not support taxation. It would display the customer that they are paying this much as tax.

**Comment by Ma7eer** [comment]
> It would be really good if the tax amount could be passed as a separate line item in Thawani since Thawani currently does not support taxation. It would display the customer that they are paying this much as tax.

Thank you @ghulamostafa I will highlight this to the team

**Comment by mariamalbalushi** [comment]
@ghulamostafa I marked this issue as won't fix and that is due to Thawani policy of not accepting less than 100 baisa products and if the total price is less than that 2 rials( tax will be less than 100 baisa) the endpoints will fail
