### ISSUE TITLE
custom integration between WooCommerce Subscriptions and Thawani Pay

### ISSUE THREAD

**Issue by k6111** [PhazeRoOman/thawani-for-woocommerce#99]
السلام عليكم

I would like to inquire! Can this plugin be activated with WooCommerce Subscriptions? And is it possible to guide me on how to do this or provide an update for this plugin to make it possible to use it with WooCommerce Subscriptions?
Thank you.

**Comment by mariamalbalushi** [comment]
Hi @k6111  Thanks for reaching out to us

Subscriptions offer two methods for handling renewals Automatic renewal and Manual renewal which one is that you need to use

**Comment by w7shdev** [comment]
> السلام عليكم
> 
> I would like to inquire! Can this plugin be activated with WooCommerce Subscriptions? And is it possible to guide me on how to do this or provide an update for this plugin to make it possible to use it with WooCommerce Subscriptions? Thank you.

Hey @k6111  no the plugin does not support WooCommerce subscription plugin.

**Comment by w7shdev** [comment]
> @w7shdev thank you ..
> Is there an upcoming plan to develop the plugin to support WooCommerce subscriptions?

No there isn't at the moment and the reasons are : 

From the product perspective *thawani-for-woocommerce plugin* : 
- Adding extra feature most of the users do not need them. 
- WooCommerce subscription is paid plugin and this one is open source and free.
- We can not provide license keys for paid product for all the contributors. _Which leads to make this product a commercial one_.

**Development** here is what will happen when you maintain 1 plugin that requires or support 2 plugins: 

- Implementation of 2 checkout logic 
- keep up to date with plugins update and this one to make sure that the plugin will work without any issue.

and there are many more reasons for not adding this as a feature to the plugin. 

> Do you have any tips that might help me enable payment or subscription in Omani Rial for WooCommerce subscriptions?

Well, you will need to build a new one, you can use this plugin for starting point!

**Comment by jaifar530** [comment]
@k6111 There are many limitations with Omani(s) payments gateways (PG), myself, I don't use any of the Omani PG, I always push my clients to use GCC PG like 
https://paymentservices.amazon.com/
or 
https://www.tap.company/kw/en

Although they ask for extra fees per transaction or monthly subscription, but at least with the above payment gateways, you can get official SDKs (or plugins) from the provider themself, and no need to chase developers to re-invent the wheel again and again. Also I can get quick support when needed. 

also there are many other features you will get like subscriptions OR other feature like in-app entering card details for better UX for the app. and many more. 

I can see Omani payment gateway providers are still not up-to-date for that market need, they have totally different perspective about how the payment gateway should look like which is totally different from the global. 

in the other hand, until now there is no initiatives for putting OMR as currency for processing payment in an International Payment gateways like Paypal, https://www.2checkout.com/ or https://stripe.com/

for example, the Talabat app uses https://paymentservices.amazon.com/ 

therefore I advise you to contact https://paymentservices.amazon.com/ support and discuss with them the implementation of subscription. 

https://paymentservices.amazon.com/  support Omani riyal and they transfer the amount to Omani National bank (NBO).

**Comment by jaifar530** [comment]
@k6111 

You need to understand very important point about the subscription, it is not about asking someone to develop it for you, it is about does the payment gateway support the subscription?

The answer is thawani is not supporting the subscription , you can contact them via support WhatsApp number to ensure this..

**Comment by jaifar530** [comment]
@k6111 i advise you to contact https://paymentservices.amazon.com/ 

They have subscription feature, you can ask them to provide you plugin for WooCommerce that supports subscription.

You need to open account at National Bank Of Oman in order to register with them ..

**Comment by jaifar530** [comment]
Not all payments gateway around the world support subscription feature even if the WooCommerce feature allows.. 

All Omani payment gateways don't suppose subscription.

Enabling the subscription feature cost the companies or organisation lots of fees by the providers (visa and MasterCard). Thus only the BIG companies/organisation around the world support subscription features.

**Comment by jaifar530** [comment]
I know many websites here in oman uses payments gateways from GCC 

Note that Amazon payments services  https://paymentservices.amazon.com/ located in UAE/KSA and it supports OMR. 

Another option is to use https://tap.company it supports OMR as well. 


I tested both of them

**Comment by jaifar530** [comment]
@k6111 also https://paymentservices.amazon.com/ support in-app entering card information, so no redirect happen in your website/mobile app. This gives better UX for your end users.

**Comment by w7shdev** [comment]
@k6111 if the issue is not solved yet!

> "Error processing checkout. Please try again." I am using version 1.3.0.

please check this comment here https://github.com/PhazeRoOman/thawani-for-woocommerce/issues/90#issuecomment-1221318338 and if it's not please open a new issue.

Best of luck
